In [80]:
#basic array creation

import numpy as np

#create a 1D array
array_1d = np.array([1,2,3,4,5])
print("1d array:",array_1d)

#create a 2D array
array_2d = np.array([[1,2,3],[4,5,6 ]])
print("2D array:\n",array_2d)

#create an array with zeros
zeros_array = np.zeros((3,3))
print("zeros Arry:\n",zeros_array)

#create an array with ones
ones_array = np.ones((3,3))
print("ones Arry:\n",ones_array)




[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
1d array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
zeros Arry:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones Arry:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [81]:
#Array operation
a=np.array([1,2,3])
b=np.array([4,5,6])
#Addition
sum_array=np.add(a,b)
print("sum:",sum_array)
#Subtraction
diff_array=np.subtract(a,b)
print("difference:",diff_array)
#Multiplication
product_array=np.multiply(a,b)
print("product:",product_array)
#Divison
quotient_array=np.divide(a,b)
print("quotient:",quotient_array)


sum: [5 7 9]
difference: [-3 -3 -3]
product: [ 4 10 18]
quotient: [0.25 0.4  0.5 ]


In [103]:
#matrix multiplication
import numpy as np

# create two matrix

matrix_a=np.array([[1,2],[3,4]])
matrix_b=np.array([[5,6],[7,8]])

#matrix multiplication

matrix_product=np.dot(matrix_a,matrix_b)
print("matrix product:\n",matrix_product)


matrix product:
 [[19 22]
 [43 50]]


In [83]:
#broadcasting
import numpy as np

# create an array and scalar

array=np.array(([1,2,3]))
scalar=2

#broadcasting

broadcasted_array=array*scalar
print("Broadcasted Array:",broadcasted_array)



Broadcasted Array: [2 4 6]


In [84]:
#statistical Operation
import numpy as np

#create an array
data=np.array([1,2,3,4,5])

#mean
mean_value=np.mean(data)
print("mean:",mean_value)

#Standard deviation
std_value=np.std(data)
print("standard deviation:",std_value)

#sum
sum_value=np.sum(data)
print("sum:",sum_value)

mean: 3.0
standard deviation: 1.4142135623730951
sum: 15


In [85]:
#reshaping arrays

import numpy as np
#create a 1D array
array=np.array([1,2,3,4,5,6])

#reshap to 2*3
reshaped_array=array.reshape((2,3))
print("reshaped array:\n",reshaped_array)

#reshape to 3*2
reshaped_array=array.reshape((3,2))
print("reshaped array:\n",reshaped_array)

reshaped array:
 [[1 2 3]
 [4 5 6]]
reshaped array:
 [[1 2]
 [3 4]
 [5 6]]


In [86]:
#element-wise operation

import numpy as np

#create two arrays
arrays_a=np.array([1,2,3])
arrays_b=np.array([4,5,6])

#Element-wise addition
add_result=arrays_a+arrays_b
print("element-wise addition:",add_result)

#Element-wise multiplication
multiply_result=arrays_a*arrays_b
print("element-wise multiplication :",multiply_result)

element-wise addition: [5 7 9]
element-wise multiplication : [ 4 10 18]


In [87]:
#Slicing and indexing
import numpy as np

#create 2D arrays
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

#accessing an element
element=array_2d[1,1]
print("Element at [1,1:]",element)

#Accessing a row
row=array_2d[1,:]
print("row 1:",row)

#Accessing a column
column=array_2d[:,1]
print("column 1:",column)


Element at [1,1:] 5
row 1: [4 5 6]
column 1: [2 5 8]


In [88]:
#creating reandom arrays
import numpy as np

#create a random array
random_array=np.random.rand(3,3)
print("random array:\n",random_array)

#create a random intrger array
random_int_array=np.random .randint(0,10,(3,3))
print("random integer array:\n",random_int_array)


random array:
 [[0.87732187 0.40288073 0.77208607]
 [0.09387952 0.79046376 0.2394778 ]
 [0.03856122 0.74342406 0.60197651]]
random integer array:
 [[3 1 1]
 [4 4 1]
 [6 4 3]]


In [89]:
#Stacking and concatending Arrays
import numpy as np

#create 2 arrays
arrays_a=np.array([1,2,3])
arrays_b=np.array([4,5,6])

#vertical stack
v_stack=np.vstack((arrays_a,arrays_b))
print("vertical stack:\n",v_stack)

#Horizontal Stack
h_stack=np.hstack((arrays_a,arrays_b))
print("Horizontal Stack:\n",h_stack)

vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]


In [90]:
#basic array creation
# numpy practice assignment

import numpy as np

#create an array with 10 equally spaced no. b/w 0&1
arr=np.linspace(0,1,10)
print(arr)

#create  an 1d array of 20 random integer b/w 1 and 100
random_int_array=np.random .randint(1,100,20)
print(random_int_array)

# create an 2d array with the shape (4,4) filled with the value 7
arr=np.full((4,4),7)
print(arr)

# create a 1d array of 10 element with the same value 3.14
arr=np.full (10,3.14)
print(arr)

# create an 2d array with the shape (3,3)with values ranging from 1to9
arr=np.arange(1,10).reshape(3,3)
print(arr)



[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[88 30 61 39 18 96 92 96 92 73 20  7  3 80  2 86  6 97 32 57]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [101]:
#Array Operation

import numpy as np

# create 2 array and perform element wise subtraction

arr_a=np.array([1,3,4,7,9])
arr_b=np.array([2,4,6,8,10])
diff_result=np.subtract(arr_a,arr_b)
print("elemant-wise subtraction :" ,diff_result)

#multiply array a by 3
arr_a=np.array([2,4,6,8])
multiply_result=arr_a*3
print("element-wise multiplication :",multiply_result)

#divide array a by 2
arr_a=np.array([10,20,30,40])
div_result=arr_a/2
print("element-wise division :",div_result)

#find the element-wise modulus of 2 array
arr_a=np.array([5,10,15])
arr_b=np.array([2,3,4])
mod_result=np.mod(arr_a,arr_b)
print("element-wise modulus:",mod_result)


# create 2 arays & compute the dot product

arr_a=np.array([1,2,3])
arr_b=np.array([4,5,6])
dot_result=np.dot(arr_a,arr_b)
print("Dot product :",dot_result)






elemant-wise subtraction : [-1 -1 -2 -1 -1]
element-wise multiplication : [ 6 12 18 24]
element-wise division : [ 5. 10. 15. 20.]
element-wise modulus: [1 1 3]
Dot product : 32


In [100]:
#Matrix Multiplication

import numpy as np

 #create two matrics and perform matrix multipliction

matrix_a=np.array([[2,3],[4,5]])
matrix_b=np.array([[1,0],[0,1]])
matrix_product=np.dot(matrix_a,matrix_b)
print("matrix product:\n",matrix_product)

#Multipiy a 3*3 matrix with a  3*1 vector

matrix_a=([[1,2,3],[4,5,6],[7,8,9]])
vector_b=([[10],[20],[30]])
matrix_product=np.dot(matrix_a,vector_b)
print("matrix product:\n",matrix_product)

#create a 4*4 identity matrix and multiply it by a 4*4 matrix with filled
# with random integer

identity_matrix=np.eye(4)
random_matrix=np.random.randint(1,10,(4,4))
result_matrix=np.dot(identity_matrix,random_matrix)
print("Identity Matrix:\n",identity_matrix)
print("Random matrix:\n",random_matrix)
print("Result Matrix:\n",result_matrix)


#perform matrix multiplication on two 3*3 matrix
matrix_a=([[1,2,3],[4,5,6],[7,8,9]])
matrix_b=([[9,8,7],[6,5,4],[3,2,1]])
matrix_product=np.dot(matrix_a,matrix_b)
print("matrix product:\n",matrix_product)

#create a 2*3 MATRIX AND a 3*2 matrix and perform multiplication
matrix_a=([[1,2,3,],[4,5,6]])
matrix_b=([[7,8],[9,10],[11,12]])
matrix_product=np.dot(matrix_a,matrix_b)
print("matrix product:\n",matrix_product)


matrix product:
 [[2 3]
 [4 5]]
matrix product:
 [[140]
 [320]
 [500]]
Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random matrix:
 [[9 3 8 8]
 [8 1 2 7]
 [4 1 2 3]
 [7 8 4 8]]
Result Matrix:
 [[9. 3. 8. 8.]
 [8. 1. 2. 7.]
 [4. 1. 2. 3.]
 [7. 8. 4. 8.]]
matrix product:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
matrix product:
 [[ 58  64]
 [139 154]]


In [93]:
# BROADCASTING

import numpy as np

 #create a 1D array and subtract a scalar value 5 using broadcasting

array=np.array([10,20,30])
scalar=5

broadcasted_array=array-scalar
print("Broadcasted Array:\n",broadcasted_array)

#create a 3*3 array and 3*1 array,and add them

array_a=np.array([[1,2,3],[4,5,6],[7,8,9]])
array_b=np.array([[1,2,3]])
broadcasted_array=array_a*array_b
print("Broadcasted Array:\n",broadcasted_array)

#Divide a 4*4 array by a scalar value 2

array_a=np.array([[1,2,3,1],[4,5,6,1],[7,8,9,1],[10,20,30,1]])
saclar=2
broadcasted_array=array_a/scalar
print("Broadcasted Array:\n",broadcasted_array)

# create a 3*3 array and add 3 to each element

array_a=np.array([[1,2,3],[4,5,6],[7,8,9]])
scalar=3
broadcasted_array=array_a+scalar
print("Broadcasted Array:\n",broadcasted_array)

# multiply a 1D array of shape (5,) by  a 2D array of shape (5,5)
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
broadcasted_array=arr1[:np.newaxis]*arr2
print("broadcasted array:\n",broadcasted_array)

Broadcasted Array:
 [ 5 15 25]
Broadcasted Array:
 [[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
Broadcasted Array:
 [[0.2 0.4 0.6 0.2]
 [0.8 1.  1.2 0.2]
 [1.4 1.6 1.8 0.2]
 [2.  4.  6.  0.2]]
Broadcasted Array:
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
broadcasted array:
 [[  1   4   9  16  25]
 [  6  14  24  36  50]
 [ 11  24  39  56  75]
 [ 16  34  54  76 100]
 [ 21  44  69  96 125]]


In [94]:

#Statical operation

import numpy as np

#calculate the median of the median of the array

data=np.array([1,2,3,4,5,6,7,8,9,10])
median_value=np.median(data)
print("median:",median_value)

#calculate the mode of the array
from scipy import stats
data=np.array([1,2,2,3,4,4,4,5,6])
mode_value=stats.mode(data)
print("mode:",mode_value)

#calculate the range of the array
data=([10,20,30,40,50])
range_value=np.ptp(data)
print("range:",range_value)

#calculate the 25 percentile of the array
data=np.array([1,2,3,4,5,6,7,8,9,10])
percentile_value=np.percentile(data,25)
print("percentile:",percentile_value)

#calcute the correlation coefficient b/w to array
data_a=np.array([1,2,3,4,5])
data_b=np.array([2,4,6,8,10])
x_result=np.corrcoef(data_a,data_b)
print("correlation coefficient:\n",x_result)

median: 5.5
mode: ModeResult(mode=4, count=3)
range: 40
percentile: 3.25
correlation coefficient:
 [[1. 1.]
 [1. 1.]]


In [95]:
#Reshaping Arrays

import numpy as np

#reshape a 1D array of 12 element to a 3*4 array

array=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped_array=array.reshape((3,4))
print("reshaped array:\n",reshaped_array)

#reshape a 2D array of shape (6,2)to(3,4)

array=np.array([[1,2],[3,4],[5,6],[7,8],[9,8],[7,6]])
reshaped_array=array.reshape((3,4))
print("reshaped array:\n",reshaped_array)

#create a 4*4 array and flatten it
array=np.array([[1,2,3,4],[2,4,6,8],[5,6,7,8],[9,8,7,6]])
flattened_value=array.flatten()
print("original array;\n",array)
print("flattened array:\n",flattened_value)

# reshape a 3D array of shape
arr=np.arange(24).reshape(2,3,4)
reshaped_array=arr.reshape((4,3,2))
print("original array;\n",array)
print("reshaped array:\n",reshaped_array)

#reshape a 1D array to a 2d array with 1 row and many columns


array=np.array([1,2,3,4,5,6,7,8])
reshaped_array=array.reshape((1,-1))
print("reshaped array:\n",reshaped_array)


reshaped array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshaped array:
 [[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]]
original array;
 [[1 2 3 4]
 [2 4 6 8]
 [5 6 7 8]
 [9 8 7 6]]
flattened array:
 [1 2 3 4 2 4 6 8 5 6 7 8 9 8 7 6]
original array;
 [[1 2 3 4]
 [2 4 6 8]
 [5 6 7 8]
 [9 8 7 6]]
reshaped array:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
reshaped array:
 [[1 2 3 4 5 6 7 8]]


In [96]:
#ELEMENT-WISE OPERATION
import numpy as np

#create two array end perform division
arr_a=np.array([1,3,5])
arr_b=np.array([2,4,6])
div_result=(arr_a/arr_b)
print("element-wise division :",div_result)

#create two array end perform modulus
arr_b=np.array([1,3,5])
arr_a=np.array([2,4,6])
mod_result=np.mod(arr_a,arr_b)
print("element-wise modulus:",mod_result)

#add 10 to each element in the array
arr=np.array([1,2,3,4,5])
sum_result=arr+10
print("element-wise addition :",sum_result)

#subtract 5 to each element in the array
arr=np.array([10,20,30,40,50])
diff_result=arr-5
print("element-wise subtraction :",diff_result)


#square of each element
arr_c=np.array([1,2,3,4,5])
squ_result=arr_c**2
print("square of each element:",squ_result)


element-wise division : [0.5        0.75       0.83333333]
element-wise modulus: [0 1 1]
element-wise addition : [11 12 13 14 15]
element-wise subtraction : [ 5 15 25 35 45]
square of each element: [ 1  4  9 16 25]


In [97]:
#SLICING AND INDEXING
import numpy as np

#create 3D array access the element[1,1,1]
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
element=arr_3d[1,1,1]
print("Element at [1,1,1]:",element)

#slice the first layer ofa 3d array
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
element=arr_3d[0]
print("Element at:\n",element)

#access all element in the last row of the array
arr_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
element=arr_2d[-1]
print("last row:\n",element)

#access all element in the first column of the array
arr_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
element=arr_2d[:,0]
print("first column:\n",element)

#slice the last two rows and column of the array
arr_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
element=arr_2d[-2:,-2:]
print("original array;\n",arr_2d)
print("last 2 row ans column:\n",element)


Element at [1,1,1]: 11
Element at:
 [[1 2 3]
 [4 5 6]]
last row:
 [70 80 90]
first column:
 [10 40 70]
original array;
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
last 2 row ans column:
 [[50 60]
 [80 90]]


In [98]:
#CREATING RANDOM ARRAYS
import numpy as np

#genetate a random array of 20 element with values b/w 0 & 1
random_array=np.random.randint(0,1,20)
print("random array:",random_array)

#create a 4*4 array with integer b/w 10 and 20
random_array=np.random.randint(10,20,(4,4))
print("random array:\n",random_array)

#create a 3*3 array with integer b/w -1and 1
lower_bound=-1
upper_bound=1
random_array=np.random.rand(3,3)*(upper_bound-lower_bound)+lower_bound
print("random array:\n",random_array)

#genetate a random array of 15 element with values b/w 100 and 200
random_array=np.random.randint(100,200,15)
print("random array:\n",random_array)


#create a 5*5 array with integer b/w 0 and 10
lower_bound=0
upper_bound=10
random_array=np.random.rand(5,5)*(upper_bound-lower_bound)+lower_bound
print("random array:\n",random_array)



random array: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
random array:
 [[19 14 12 12]
 [16 17 15 19]
 [18 12 14 17]
 [17 15 19 16]]
random array:
 [[-0.07257105  0.28382144  0.10876495]
 [-0.13392976 -0.71790583  0.59008029]
 [ 0.85846034 -0.90875687  0.06851639]]
random array:
 [166 169 167 162 197 196 103 103 126 151 125 114 184 187 167]
random array:
 [[1.26109671 1.12300114 6.07220466 6.3450583  4.81438774]
 [6.26130361 8.19067717 0.85697684 6.74975457 9.44995942]
 [6.88787827 4.65288984 2.830947   8.24994955 8.29088987]
 [5.61322112 8.43177171 0.29922873 2.0723679  6.02265894]
 [4.9474572  4.11105864 6.86945583 8.0944691  8.7052903 ]]


In [99]:
#STACKING AND CONCATENATING ARRAYS
import numpy as np

#vertically stack 2 arrays
arr_a=np.array([[1,2],[3,4]])
arr_b=np.array([[5,6],[7,8]])
v_stack=np.vstack((arr_a,arr_b))
print("vertical stack:\n",v_stack)

#Horizontal Stack 2 arrays
arr_a=np.array([[1,2],[3,4]])
arr_b=np.array([[5,6],[7,8]])
h_stack=np.hstack((arr_a,arr_b))
print("Horizontal Stack:\n",h_stack)


#concatenate two 1D arrays
arr_a=np.array([1,2,3])
arr_b=np.array([4,5,6])
concatenate_arr=np.concatenate((arr_a,arr_b))
print("concatenate arrays:\n",concatenate_arr)


#concatenate two 3*3 arrays along rows
arr_a=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_b=np.array([[10,11,12],[13,14,15],[16,17,18]])
concatenate_arr=np.concatenate((arr_a,arr_b),axis=0)
print("concatenate arrays:\n",concatenate_arr)



#concatenate two 3*3 arrays along columns
arr_a=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_b=np.array([[10,11,12],[13,14,15],[16,17,18]])
concatenate_arr=np.concatenate((arr_a,arr_b),axis=1)
print("concatenate arrays:\n",concatenate_arr)

vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
concatenate arrays:
 [1 2 3 4 5 6]
concatenate arrays:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
concatenate arrays:
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
